### ISSUE TITLE
Imposible make it work in Noetic (due python version maybe)

### ISSUE THREAD

**Issue by FPSychotic** [StephLin/LIO-SEGMOT#11]
Hi , I could make install lio-segmot in ubuntu 20.04 with some small modification, but 
[livox_detection_lio_segmot](https://github.com/StephLin/livox_detection_lio_segmot)
and 
[StephLin/SE-SSD-ROS (Apache-2.0 license)](https://github.com/StephLin/SE-SSD-ROS) (based on [Vegeta2020/SE-SSD](https://github.com/Vegeta2020/SE-SSD))
depends of 18.04 python dependencies as h5py, numpy 1.20 etc and I cannot make it work.

Is there any plan to make it work in Ubuntu 20.04 with actual dependencies that make it possible install?
Thanks !!

**Comment by StephLin** [comment]
I do not work on landing LIO-SEGMOT on Ubuntu 20.04 yet. However, it would be great if you can make it work on Ubuntu 20.04. Can you share your method with us? (Even a PR is better!)

I believe that both detection models can be executed on Ubuntu 20.04 with [Docker](https://www.docker.com/) and [nvidia-docker](https://github.com/NVIDIA/nvidia-docker). They already have dockerfiles ([livox_detection](https://github.com/StephLin/livox_detection_lio_segmot/blob/detection_v1.1_lio_segmot/Dockerfile), [SE-SSD](https://github.com/StephLin/SE-SSD-ROS/blob/main/Dockerfile)) and setup guides ([livox_detection](https://github.com/StephLin/livox_detection_lio_segmot#installation-docker), [SE-SSD](https://github.com/StephLin/SE-SSD-ROS#installation-docker)). You can refer to them for more information.
