### ISSUE TITLE
cuda10.2换成cuda11.2

### ISSUE THREAD

**Issue by CTT520** [StephLin/LIO-SEGMOT#13]
你好，请问在安装动态物体检测服务端SE-SSD-ROS步骤中，要求torch和torchvision是和cuda10.2版本相匹配的，但是我的30系显卡不支持cuda11.0以下的版本，安装cuda11.2以及对应的torch+torchvision可以吗

**Comment by StephLin** [comment]
Hi @CTT520,

你可以使用支援 CUDA 11+ 的 PyTorch 1.6.x 版本執行 SD-SSD-ROS.
通常這個版本需要自行編譯，不過如果你的環境可以使用 Docker，可以考慮使用 nvidia-docker，流程可參考 https://github.com/StephLin/SE-SSD-ROS/tree/main?tab=readme-ov-file#installation-docker
