### ISSUE TITLE
Run separate programs that under src folder

### ISSUE THREAD

**Issue by YS-Huang612** [StephLin/LIO-SEGMOT#14]
Hi, I'd like to run separate programs that under src folder (For example, "featureExtraction.cpp" or any other programs). It could help me to do other experiments. Is there any idea that help me to do this? Cause if I follow the instructions on README, it'll only show the final result. Thanks!

**Comment by StephLin** [comment]
Hi @YS-Huang612,

Perhaps you can modify lunch files to do that. There are 4 programs in LIO-SEGMOT currently, and you can remove unwanted programs:

https://github.com/StephLin/LIO-SEGMOT/blob/ff72a8906bb7ef0fba17b0d419e1a15260e4e1b5/launch/include/module_loam.launch#L5-L8
