### ISSUE TITLE
Timestamp not available problem occurs when running bag package

### ISSUE THREAD

**Issue by dkjsednfkjsn** [StephLin/LIO-SEGMOT#15]
Hello, because the author's bag link cannot be downloaded, I used the kitti2bag file provided to get the data set, but after running it, an error "Point cloud timestamp not available, deskew function disabled, system will drift significantly!" will be reported. Please ask this question. Is it because the kittibag package I am using does not have a timestamp?

**Comment by dkjsednfkjsn** [comment]
This problem has been solved, but I am currently encountering the problem of running stuck. I ran the kitti_2011_09_26_drive_0009_synced.bag file, but the output to [INFO] [1708612962.047199812]: Remaining patches: 439 produced the following error "[lio_segmot_mapOptimization-4] process has died ”, how to solve this problem?

**Comment by dkjsednfkjsn** [comment]
[
![11](https://github.com/StephLin/LIO-SEGMOT/assets/82888967/7b223ffd-2a13-4168-82d7-68077ece7ad5)
![22](https://github.com/StephLin/LIO-SEGMOT/assets/82888967/ce278ab1-3da5-4ab1-a11c-ea2090aa06c6)

**Comment by StephLin** [comment]
Hi @dkjsednfkjsn,

Sorry for the late reply 😥

1. I'll update the download link ASAP. Thanks for your kind reminder.
2. As for the dead process, perhaps you could check out the failed log first. In your snapshots it should be located at `/home/dhw/.ros/log/6d37...1c28/lio_segmot_mapOptimization-4.log`. Please feel free to paste the content here if you could not resolve the issue based on it's error messages.

**Comment by dkjsednfkjsn** [comment]
> 你好@dkjsednfkjsn,
> 
> 抱歉回复晚了😥
> 
> 1. 我会尽快更新下载链接。谢谢你的好意提醒。
> 2. 至于死进程，也许你可以先查看失败的日志。在您的快照中，它应该位于`/home/dhw/.ros/log/6d37...1c28/lio_segmot_mapOptimization-4.log`。如果您无法根据错误消息解决问题，请随时将内容粘贴到此处。

Thank you for your reply. This problem has been solved. There was a problem with the rosbag file I made before. I hope you can download your own data set for testing and comparison. Thank you again for your work!

**Comment by dkjsednfkjsn** [comment]
> 你好@dkjsednfkjsn,
> 
> 抱歉回复晚了😥
> 
> 1. 我会加速更新下载链接。谢谢你的好意提醒。
> 2. 至于死进程，也许你可以先查看失败的日志。在您的快照中，它应该位于`/home/dhw/.ros/log/6d37...1c28/lio_segmot_mapOptimization-4.log`。如果您无法根据错误消息解决问题，请随时将内容粘贴到此处。

Thank you for your reply. This problem has been solved. There was a problem with the rosbag file I made before. I wish I can download your own dataset for testing and comparison. Thank you again for your work!

**Comment by XYJ88888** [comment]
> > 你好@dkjsednfkjsn,
> > 抱歉回复晚了😥
> > 
> > 1. 我会加速更新下载链接。谢谢你的好意提醒。
> > 2. 至于死进程，也许你可以先查看失败的日志。在您的快照中，它应该位于`/home/dhw/.ros/log/6d37...1c28/lio_segmot_mapOptimization-4.log`。如果您无法根据错误消息解决问题，请随时将内容粘贴到此处。
> 
> Thank you for your reply. This problem has been solved. There was a problem with the rosbag file I made before. I wish I can download your own dataset for testing and comparison. Thank you again for your work!
> 
> > 你好@dkjsednfkjsn，
> > 抱歉回复晚了😥
> > 
> > 1. I'll get up to update the download link.谢谢你的好意提醒。
> > 2. In this paper，we study the relationship between the factors of the factors.在您的快照中，它应该位于`/home/dhw/.ros/log/6d37...1c28/lio_segmot_mapOptimization-4.log`.如果您无法根据错误消息解决问题，请随时将内容粘贴到此处。
> 
> 感谢您的回复。这个问题已经解决了。我之前做的rosbag文件有问题。我希望我可以下载你自己的数据集进行测试和比较。再次感谢您的工作！

I also encountered this problem. How did you solve it?

**Comment by JJho1314** [comment]
I also encountered this problem. How did you solve it?

**Comment by Wwt15537588047** [comment]
Can you tell me how to solve the timestamp probloem.
