### ISSUE TITLE
启动SE-SEG-ROS与

### ISSUE THREAD

**Issue by XYJ88888** [StephLin/LIO-SEGMOT#17]
使用python3 ros_main.py --mode lio_segmot会报错
进不去def __call__(self, cloud_msg: PointCloud2):这个函数，mapping里面发出的原始点云信息是正常的。

**Comment by XYJ88888** [comment]
![Uploading 2024-03-20 20-01-51 的屏幕截图.png…]()

**Comment by XYJ88888** [comment]
![02af183ff81fb25f963d08e52f7adb6](https://github.com/StephLin/LIO-SEGMOT/assets/131513634/8ab5e68a-e6ae-4cec-87e1-d5fc2b758624)

**Comment by StephLin** [comment]
Hi @XYJ88888,

You should source LIO-SEGMOT's environment before running SE-SSD-ROS with LIO-SEGMOT mode.

Similar issue: https://github.com/StephLin/SE-SSD-ROS/issues/13
