### ISSUE TITLE
Run UrbanNav dataset

### ISSUE THREAD

**Issue by XYJ88888** [StephLin/LIO-SEGMOT#19]
When running UrbanNav dataset, target detection has a large error. If you try to train a model with point clouds from other UrbanNav datasets, can you get good detection results?

**Comment by XYJ88888** [comment]
Run the Hsinchu dataset the same way, detect errors, do I need to make my own model? I use the student model given by se-ssd. Could you share your model if it is convenient?
![Uploading IMG_20240415_184755.png…]()

**Comment by XYJ88888** [comment]
Run the Hsinchu dataset the same way, detect errors, do I need to make my own model? I use the student model given by se-ssd. Could you share your model if it is convenient?
![Uploading 1713178361448.jpg…]()

**Comment by XYJ88888** [comment]
Run the Hsinchu dataset the same way, detect errors, do I need to make my own model? I use the student model given by se-ssd. Could you share your model if it is convenient?
![IMG_20240415_184755](https://github.com/StephLin/LIO-SEGMOT/assets/131513634/89929e3b-b08b-4d15-8dd0-b6fd8302bd3a)

**Comment by XYJ88888** [comment]
> Hi @XYJ88888,
> 
> I use [Livox detection](https://github.com/StephLin/livox_detection_lio_segmot) in Hsinchu dataset. Its performance should be better. Sorry that I'm not familiar with UrbanNav dataset, while you may give the above detector a try.

Thanks for your reply, Livox detection only detects Livox radar? Does it work on mechanical radar?

**Comment by StephLin** [comment]
> > Hi @XYJ88888,
> > I use [Livox detection](https://github.com/StephLin/livox_detection_lio_segmot) in Hsinchu dataset. Its performance should be better. Sorry that I'm not familiar with UrbanNav dataset, while you may give the above detector a try.
> 
> Thanks for your reply, Livox detection only detects Livox lidar? Does it work on mechanical radar?

My experiments show it works (not perfect but acceptable).
