### ISSUE TITLE
Forget the old tracking points

### ISSUE THREAD

**Issue by mantruong204** [StephLin/LIO-SEGMOT#20]
Thanks for a hard work,
Is there a mechanism in mapOptimization that let the system forget the old tracked objects (like the map in LIO-SAM erases the old keyframe). My computer get lag when operating LIO-SEGMOT for a long time with the detector ON. 
Thank you!

**Comment by StephLin** [comment]
Hi @mantruong204,

I'm sorry that this repo does not have this feature yet. 😥

A simple solution to prevent performance degradation is to use the offline replay node, whereas a better way (somehow) is applying marginalization on previous tracked objects. However currently I have limited time to implement it.

**Comment by mantruong204** [comment]
Thanks for you reply,
Maybe, it could be an idea for future improvement.
Have a nice day!
