### ISSUE TITLE
EVO difference

### ISSUE THREAD

**Issue by XYJ88888** [StephLin/LIO-SEGMOT#21]
Hello, I reproduced your results in kitti dataset, and found that the errors of LIO-SAM algorithm and LIO-SEGMOT algorithm I ran were larger than those of your paper, especially in 09_26_0101 dataset. Did you make any modifications to parameters during data processing?

**Comment by XYJ88888** [comment]
Using Livox's detector takes a bit of time。

**Comment by StephLin** [comment]
Hi @XYJ88888,

Something you may be able to checkout first:

1. Did you run LIO-SEGMOT with KITTI config: `roslaunch lio_segmot run_kitti.launch`?
2. Did you replay both LIO-SAM and LIO-SEGMOT with the offline replay node: `rosrun lio_segmot lio_segmot_offlineBagPlayer _bag_filename:="path/to/your/sequence.bag"`
3. The KITTI results provided in the paper is based on SE-SSD. You may take a look on [SE-SSD-ROS](https://github.com/StephLin/SE-SSD-ROS) to see how it interact with LIO-SEGMOT.
