### ISSUE TITLE
Sample Datasets

### ISSUE THREAD

**Issue by Zhaohuanfeng** [StephLin/LIO-SEGMOT#8]
I can not download the Sample Datasets in China, even if I use VPN. Can other download channels be provided？

**Comment by StephLin** [comment]
Hi @Zhaohuanfeng,

Could you connect to Google drive? Give it a try: https://drive.google.com/drive/folders/1RLlUKq8uiro6-5HY6m3lVcppJxYDuNAX?usp=share_link

**Comment by Zhaohuanfeng** [comment]
Thank you very much. Now I can download the dataset！！！
